export const quotes = [
  // 🌿 Calm (50 quotes)
  { text: "Peace is not something you find. It is something you allow.", author: "Elia Laurent", category: "calm" },
  { text: "Slow down. The soul moves at a gentler pace than the world.", author: "Mira Solene", category: "calm" },
  { text: "Silence is where clarity begins to bloom.", author: "Armand Vale", category: "calm" },
  { text: "You do not have to rush the version of you that is unfolding.", author: "Celine Aure", category: "calm" },
  { text: "Calm is a quiet kind of strength.", author: "Theo Maris", category: "calm" },
  { text: "Let the day soften around you.", author: "Isla Ren", category: "calm" },
  { text: "Stillness is not empty. It is full of answers.", author: "Lucien Artois", category: "calm" },
  { text: "Breathe as if the moment is enough.", author: "Noelle Serein", category: "calm" },
  { text: "There is no emergency in becoming.", author: "Elio Marchand", category: "calm" },
  { text: "Peace enters when control leaves.", author: "Sabine Moreau", category: "calm" },
  { text: "Rest is productive when it restores your spirit.", author: "Julian Hart", category: "calm" },
  { text: "A quiet mind hears what chaos never could.", author: "Anaïs Bloom", category: "calm" },
  { text: "You are allowed to move gently through hard days.", author: "Orion Wells", category: "calm" },
  { text: "Calm is a decision made in whispers.", author: "Fleur Bennett", category: "calm" },
  { text: "Nothing grows well in constant urgency.", author: "Adrian Sol", category: "calm" },
  { text: "Let yourself arrive slowly.", author: "Camille Rowe", category: "calm" },
  { text: "The nervous heart learns peace in patience.", author: "Elias Monroe", category: "calm" },
  { text: "Softness is not weakness. It is wisdom.", author: "Rosalie Verne", category: "calm" },
  { text: "Your breath is a doorway back to yourself.", author: "Mateo Quinn", category: "calm" },
  { text: "The sky never hurries, yet it changes beautifully.", author: "Liora Dane", category: "calm" },
  { text: "Be steady, not perfect.", author: "Vincent Hale", category: "calm" },
  { text: "A gentle life is still a powerful one.", author: "Mae Laurent", category: "calm" },
  { text: "Pause. The world can wait.", author: "Daniel Croix", category: "calm" },
  { text: "Calm begins where comparison ends.", author: "Aria Linden", category: "calm" },
  { text: "Peace tastes like acceptance.", author: "Soren Vale", category: "calm" },
  { text: "Let your shoulders forgive the weight.", author: "Celeste Marin", category: "calm" },
  { text: "The quiet version of you is still worthy.", author: "Hugo Delacour", category: "calm" },
  { text: "Serenity is self-trust in action.", author: "Elise Rowan", category: "calm" },
  { text: "Not every thought deserves your energy.", author: "Nico Arden", category: "calm" },
  { text: "The art of living is the art of slowing.", author: "Clara Fontaine", category: "calm" },
  { text: "You are safe in this breath.", author: "Leo Beaumont", category: "calm" },
  { text: "Gentle days build resilient hearts.", author: "Ivy Solis", category: "calm" },
  { text: "Calm is the courage to release.", author: "Adrian Wolfe", category: "calm" },
  { text: "Still water reflects the truest image.", author: "Mira Laurent", category: "calm" },
  { text: "Let the noise pass through you, not live in you.", author: "Emile Hart", category: "calm" },
  { text: "Peace does not shout. It settles.", author: "Nora Vale", category: "calm" },
  { text: "Take life in smaller sips.", author: "Julien Armand", category: "calm" },
  { text: "Even storms bow to silence eventually.", author: "Seraphine Cole", category: "calm" },
  { text: "Your pace is valid.", author: "Theo Linden", category: "calm" },
  { text: "Rest your mind like you rest your body.", author: "Camille Arden", category: "calm" },
  { text: "The present moment is a gentle place.", author: "Elias Moreau", category: "calm" },
  { text: "Calm grows in the soil of trust.", author: "Anais Laurent", category: "calm" },
  { text: "Choose softness when you can.", author: "Lucas Fontaine", category: "calm" },
  { text: "Nothing essential is ever rushed.", author: "Isabelle Hart", category: "calm" },
  { text: "Let today be simple.", author: "Orion Vale", category: "calm" },
  { text: "Peace is permission.", author: "Mae Soren", category: "calm" },
  { text: "Release the urgency to prove.", author: "Elia Beaumont", category: "calm" },
  { text: "Quiet is a luxury you can create.", author: "Clara Moreau", category: "calm" },
  { text: "Inhale grace. Exhale pressure.", author: "Adrian Solene", category: "calm" },
  { text: "You are allowed to just be.", author: "Rosalie Dane", category: "calm" },

  // ☀️ Happy (50 quotes)
  { text: "Happiness often arrives quietly, like sunlight on the floor.", author: "Elia Laurent", category: "happy" },
  { text: "Joy is a gentle decision you make each morning.", author: "Mira Solene", category: "happy" },
  { text: "There is magic in ordinary days.", author: "Theo Maris", category: "happy" },
  { text: "Smile softly. It changes more than you think.", author: "Celine Aure", category: "happy" },
  { text: "Happiness grows where gratitude lives.", author: "Armand Vale", category: "happy" },
  { text: "Let yourself enjoy small things without guilt.", author: "Isla Ren", category: "happy" },
  { text: "Light enters when you let it.", author: "Lucien Artois", category: "happy" },
  { text: "Joy is not loud. It is steady.", author: "Noelle Serein", category: "happy" },
  { text: "Collect moments, not worries.", author: "Elio Marchand", category: "happy" },
  { text: "The heart knows how to bloom again.", author: "Sabine Moreau", category: "happy" },
  { text: "A warm cup and a quiet morning can heal a lot.", author: "Julian Hart", category: "happy" },
  { text: "Happiness is presence, not perfection.", author: "Anaïs Bloom", category: "happy" },
  { text: "Even soft laughter counts as sunshine.", author: "Orion Wells", category: "happy" },
  { text: "Joy feels like exhaling fully.", author: "Fleur Bennett", category: "happy" },
  { text: "Let today surprise you gently.", author: "Adrian Sol", category: "happy" },
  { text: "There is sweetness in simply being alive.", author: "Camille Rowe", category: "happy" },
  { text: "Choose what feels light.", author: "Elias Monroe", category: "happy" },
  { text: "A peaceful heart is a happy one.", author: "Rosalie Verne", category: "happy" },
  { text: "Your smile is a form of hope.", author: "Mateo Quinn", category: "happy" },
  { text: "Bright days begin within.", author: "Liora Dane", category: "happy" },
  { text: "You deserve uncomplicated joy.", author: "Vincent Hale", category: "happy" },
  { text: "Find delight in slow mornings.", author: "Mae Laurent", category: "happy" },
  { text: "Happiness does not require permission.", author: "Daniel Croix", category: "happy" },
  { text: "Laugh without overthinking it.", author: "Aria Linden", category: "happy" },
  { text: "Joy multiplies when shared.", author: "Soren Vale", category: "happy" },
  { text: "Let your eyes notice beauty.", author: "Celeste Marin", category: "happy" },
  { text: "Sunlight exists even behind clouds.", author: "Hugo Delacour", category: "happy" },
  { text: "A grateful heart glows differently.", author: "Elise Rowan", category: "happy" },
  { text: "Your happiness matters.", author: "Nico Arden", category: "happy" },
  { text: "Even tiny progress feels good.", author: "Clara Fontaine", category: "happy" },
  { text: "Bloom where you are.", author: "Leo Beaumont", category: "happy" },
  { text: "Joy is found in gentle awareness.", author: "Ivy Solis", category: "happy" },
  { text: "Celebrate small wins.", author: "Adrian Wolfe", category: "happy" },
  { text: "The day smiles back when you do.", author: "Mira Laurent", category: "happy" },
  { text: "Pleasure lives in presence.", author: "Emile Hart", category: "happy" },
  { text: "Let laughter soften your edges.", author: "Nora Vale", category: "happy" },
  { text: "Life can be light.", author: "Julien Armand", category: "happy" },
  { text: "You are allowed to feel good.", author: "Seraphine Cole", category: "happy" },
  { text: "Choose joy, even quietly.", author: "Theo Linden", category: "happy" },
  { text: "Moments of happiness are never wasted.", author: "Camille Arden", category: "happy" },
  { text: "Happiness is a daily practice.", author: "Elias Moreau", category: "happy" },
  { text: "Let your heart feel warm.", author: "Anais Laurent", category: "happy" },
  { text: "You carry light within you.", author: "Lucas Fontaine", category: "happy" },
  { text: "Simple joys are sacred.", author: "Isabelle Hart", category: "happy" },
  { text: "The present holds sweetness.", author: "Orion Vale", category: "happy" },
  { text: "Joy begins with acceptance.", author: "Mae Soren", category: "happy" },
  { text: "Notice what makes you smile.", author: "Elia Beaumont", category: "happy" },
  { text: "Bright thoughts build bright days.", author: "Clara Moreau", category: "happy" },
  { text: "Let yourself feel lucky.", author: "Adrian Solene", category: "happy" },
  { text: "Happiness looks good on you.", author: "Rosalie Dane", category: "happy" },

  // 💕 Romantic (50 quotes)
  { text: "Love feels safest when it is gentle.", author: "Elia Laurent", category: "romantic" },
  { text: "You entered my life like calm after rain.", author: "Mira Solene", category: "romantic" },
  { text: "Romance is attention, not intensity.", author: "Theo Maris", category: "romantic" },
  { text: "I choose you in quiet ways.", author: "Celine Aure", category: "romantic" },
  { text: "Your presence feels like home.", author: "Armand Vale", category: "romantic" },
  { text: "Love does not rush. It stays.", author: "Isla Ren", category: "romantic" },
  { text: "You are my favorite calm.", author: "Lucien Artois", category: "romantic" },
  { text: "The softest love lasts the longest.", author: "Noelle Serein", category: "romantic" },
  { text: "With you, silence feels full.", author: "Elio Marchand", category: "romantic" },
  { text: "I knew it was love when I felt safe.", author: "Sabine Moreau", category: "romantic" },
  { text: "Your hand in mine makes the world softer.", author: "Julian Hart", category: "romantic" },
  { text: "Real romance is consistency.", author: "Anaïs Bloom", category: "romantic" },
  { text: "You look at me like I matter.", author: "Orion Wells", category: "romantic" },
  { text: "Love is found in small, repeated gestures.", author: "Fleur Bennett", category: "romantic" },
  { text: "I do not want fireworks. I want warmth.", author: "Adrian Sol", category: "romantic" },
  { text: "Your voice feels like evening light.", author: "Camille Rowe", category: "romantic" },
  { text: "To be loved gently is a blessing.", author: "Elias Monroe", category: "romantic" },
  { text: "Stay with me in the ordinary.", author: "Rosalie Verne", category: "romantic" },
  { text: "Love should feel like exhaling.", author: "Mateo Quinn", category: "romantic" },
  { text: "You are my quiet favorite.", author: "Liora Dane", category: "romantic" },
  { text: "Romance lives in the details.", author: "Vincent Hale", category: "romantic" },
  { text: "I fall for you in slow motion.", author: "Mae Laurent", category: "romantic" },
  { text: "With you, time behaves differently.", author: "Daniel Croix", category: "romantic" },
  { text: "Your love steadies me.", author: "Aria Linden", category: "romantic" },
  { text: "I choose tenderness over drama.", author: "Soren Vale", category: "romantic" },
  { text: "You are the softness I prayed for.", author: "Celeste Marin", category: "romantic" },
  { text: "Love is patience in action.", author: "Hugo Delacour", category: "romantic" },
  { text: "You make my guarded heart gentle.", author: "Elise Rowan", category: "romantic" },
  { text: "I feel seen with you.", author: "Nico Arden", category: "romantic" },
  { text: "Romance is remembering.", author: "Clara Fontaine", category: "romantic" },
  { text: "You are the calm in my chest.", author: "Leo Beaumont", category: "romantic" },
  { text: "Let us love slowly.", author: "Ivy Solis", category: "romantic" },
  { text: "I admire the way you care.", author: "Adrian Wolfe", category: "romantic" },
  { text: "With you, love feels steady.", author: "Mira Laurent", category: "romantic" },
  { text: "Your kindness is irresistible.", author: "Emile Hart", category: "romantic" },
  { text: "I trust the way you love.", author: "Nora Vale", category: "romantic" },
  { text: "You feel like certainty.", author: "Julien Armand", category: "romantic" },
  { text: "Love deepens in gentleness.", author: "Seraphine Cole", category: "romantic" },
  { text: "I find comfort in your nearness.", author: "Theo Linden", category: "romantic" },
  { text: "You are the warmth I did not know I needed.", author: "Camille Arden", category: "romantic" },
  { text: "Romance is safety wrapped in affection.", author: "Elias Moreau", category: "romantic" },
  { text: "You make love feel simple.", author: "Anais Laurent", category: "romantic" },
  { text: "My heart relaxes around you.", author: "Lucas Fontaine", category: "romantic" },
  { text: "Love is a quiet promise.", author: "Isabelle Hart", category: "romantic" },
  { text: "I would choose you in every season.", author: "Orion Vale", category: "romantic" },
  { text: "Tender love transforms.", author: "Mae Soren", category: "romantic" },
  { text: "With you, I soften.", author: "Elia Beaumont", category: "romantic" },
  { text: "Love is calm commitment.", author: "Clara Moreau", category: "romantic" },
  { text: "You are my favorite 'what if' turned real.", author: "Adrian Solene", category: "romantic" },
  { text: "To love you is to feel at peace.", author: "Rosalie Dane", category: "romantic" },

  // 🔥 Motivation (50 quotes)
  { text: "I do not chase. I build.", author: "Elia Laurent", category: "motivation" },
  { text: "Confidence is quiet proof.", author: "Mira Solene", category: "motivation" },
  { text: "I am becoming undeniable.", author: "Theo Maris", category: "motivation" },
  { text: "Discipline is self-respect in action.", author: "Celine Aure", category: "motivation" },
  { text: "I move with purpose, not pressure.", author: "Armand Vale", category: "motivation" },
  { text: "Success responds to consistency.", author: "Isla Ren", category: "motivation" },
  { text: "I trust my preparation.", author: "Lucien Artois", category: "motivation" },
  { text: "Power begins with decision.", author: "Noelle Serein", category: "motivation" },
  { text: "I do not shrink to fit.", author: "Elio Marchand", category: "motivation" },
  { text: "My standards protect my future.", author: "Sabine Moreau", category: "motivation" },
  { text: "I outgrow what underestimates me.", author: "Julian Hart", category: "motivation" },
  { text: "Execution creates confidence.", author: "Anaïs Bloom", category: "motivation" },
  { text: "I am not lucky. I am prepared.", author: "Orion Wells", category: "motivation" },
  { text: "Strength is built in silence.", author: "Fleur Bennett", category: "motivation" },
  { text: "I owe myself success.", author: "Adrian Sol", category: "motivation" },
  { text: "Focus is a form of power.", author: "Camille Rowe", category: "motivation" },
  { text: "I raise my own bar.", author: "Elias Monroe", category: "motivation" },
  { text: "Growth is uncomfortable on purpose.", author: "Rosalie Verne", category: "motivation" },
  { text: "I am committed to becoming excellent.", author: "Mateo Quinn", category: "motivation" },
  { text: "Momentum follows action.", author: "Liora Dane", category: "motivation" },
  { text: "I choose long-term over easy.", author: "Vincent Hale", category: "motivation" },
  { text: "Self-trust is my advantage.", author: "Mae Laurent", category: "motivation" },
  { text: "I am not behind. I am building.", author: "Daniel Croix", category: "motivation" },
  { text: "Results respect effort.", author: "Aria Linden", category: "motivation" },
  { text: "I refine, I improve, I rise.", author: "Soren Vale", category: "motivation" },
  { text: "My ambition is disciplined.", author: "Celeste Marin", category: "motivation" },
  { text: "I am capable of more.", author: "Hugo Delacour", category: "motivation" },
  { text: "Pressure reveals my strength.", author: "Elise Rowan", category: "motivation" },
  { text: "I lead myself first.", author: "Nico Arden", category: "motivation" },
  { text: "Consistency outperforms motivation.", author: "Clara Fontaine", category: "motivation" },
  { text: "I make bold decisions calmly.", author: "Leo Beaumont", category: "motivation" },
  { text: "I expand beyond fear.", author: "Ivy Solis", category: "motivation" },
  { text: "I invest in my potential daily.", author: "Adrian Wolfe", category: "motivation" },
  { text: "My focus is sharper than doubt.", author: "Mira Laurent", category: "motivation" },
  { text: "I do not wait for permission.", author: "Emile Hart", category: "motivation" },
  { text: "I turn discipline into destiny.", author: "Nora Vale", category: "motivation" },
  { text: "I am building a life I respect.", author: "Julien Armand", category: "motivation" },
  { text: "Excuses expire here.", author: "Seraphine Cole", category: "motivation" },
  { text: "I execute with precision.", author: "Theo Linden", category: "motivation" },
  { text: "My standards are non-negotiable.", author: "Camille Arden", category: "motivation" },
  { text: "I am steady under pressure.", author: "Elias Moreau", category: "motivation" },
  { text: "I turn setbacks into skill.", author: "Anais Laurent", category: "motivation" },
  { text: "I rise because I decide to.", author: "Lucas Fontaine", category: "motivation" },
  { text: "Confidence is earned daily.", author: "Isabelle Hart", category: "motivation" },
  { text: "I am proof of my own work.", author: "Orion Vale", category: "motivation" },
  { text: "I choose courage repeatedly.", author: "Mae Soren", category: "motivation" },
  { text: "My progress is intentional.", author: "Elia Beaumont", category: "motivation" },
  { text: "I am aligned with excellence.", author: "Clara Moreau", category: "motivation" },
  { text: "I respect the grind.", author: "Adrian Solene", category: "motivation" },
  { text: "I am powerful because I persist.", author: "Rosalie Dane", category: "motivation" },

  // 🌙 Reflective (50 quotes)
  { text: "I am responsible for the energy I carry.", author: "Elia Laurent", category: "reflective" },
  { text: "Self-awareness is freedom.", author: "Mira Solene", category: "reflective" },
  { text: "I listen to my patterns before I blame others.", author: "Theo Maris", category: "reflective" },
  { text: "Growth begins with honesty.", author: "Celine Aure", category: "reflective" },
  { text: "I cannot heal what I refuse to face.", author: "Armand Vale", category: "reflective" },
  { text: "My triggers teach me.", author: "Isla Ren", category: "reflective" },
  { text: "Maturity is choosing better, repeatedly.", author: "Lucien Artois", category: "reflective" },
  { text: "I am learning myself in layers.", author: "Noelle Serein", category: "reflective" },
  { text: "Awareness changes everything.", author: "Elio Marchand", category: "reflective" },
  { text: "I observe before I react.", author: "Sabine Moreau", category: "reflective" },
  { text: "Not every emotion deserves expression.", author: "Julian Hart", category: "reflective" },
  { text: "I take accountability without self-hate.", author: "Anaïs Bloom", category: "reflective" },
  { text: "Healing is noticing the pattern.", author: "Orion Wells", category: "reflective" },
  { text: "I protect my peace by understanding myself.", author: "Fleur Bennett", category: "reflective" },
  { text: "My boundaries reflect my self-respect.", author: "Adrian Sol", category: "reflective" },
  { text: "I can admit when I am wrong.", author: "Camille Rowe", category: "reflective" },
  { text: "Understanding myself saves me from chaos.", author: "Elias Monroe", category: "reflective" },
  { text: "Reflection is a daily discipline.", author: "Rosalie Verne", category: "reflective" },
  { text: "I pause to understand my reaction.", author: "Mateo Quinn", category: "reflective" },
  { text: "Awareness softens ego.", author: "Liora Dane", category: "reflective" },
  { text: "I am not my first impulse.", author: "Vincent Hale", category: "reflective" },
  { text: "Clarity comes from within.", author: "Mae Laurent", category: "reflective" },
  { text: "I respond from alignment, not emotion.", author: "Daniel Croix", category: "reflective" },
  { text: "Self-knowledge is power.", author: "Aria Linden", category: "reflective" },
  { text: "I examine my intentions.", author: "Soren Vale", category: "reflective" },
  { text: "I evolve beyond old habits.", author: "Celeste Marin", category: "reflective" },
  { text: "Growth requires discomfort.", author: "Hugo Delacour", category: "reflective" },
  { text: "I forgive myself and adjust.", author: "Elise Rowan", category: "reflective" },
  { text: "I recognize what drains me.", author: "Nico Arden", category: "reflective" },
  { text: "Self-awareness deepens compassion.", author: "Clara Fontaine", category: "reflective" },
  { text: "I accept my shadow without shame.", author: "Leo Beaumont", category: "reflective" },
  { text: "My reactions are my responsibility.", author: "Ivy Solis", category: "reflective" },
  { text: "I choose reflection over defensiveness.", author: "Adrian Wolfe", category: "reflective" },
  { text: "I learn from what repeats.", author: "Mira Laurent", category: "reflective" },
  { text: "I question my own narratives.", author: "Emile Hart", category: "reflective" },
  { text: "Peace follows understanding.", author: "Nora Vale", category: "reflective" },
  { text: "I own my mistakes calmly.", author: "Julien Armand", category: "reflective" },
  { text: "Insight is earned.", author: "Seraphine Cole", category: "reflective" },
  { text: "I grow beyond who I was.", author: "Theo Linden", category: "reflective" },
  { text: "Self-awareness builds self-trust.", author: "Camille Arden", category: "reflective" },
  { text: "I examine before I assume.", author: "Elias Moreau", category: "reflective" },
  { text: "I separate feelings from facts.", author: "Anais Laurent", category: "reflective" },
  { text: "I choose growth over ego.", author: "Lucas Fontaine", category: "reflective" },
  { text: "My awareness protects my future.", author: "Isabelle Hart", category: "reflective" },
  { text: "I refine my character intentionally.", author: "Orion Vale", category: "reflective" },
  { text: "Understanding myself makes me stable.", author: "Mae Soren", category: "reflective" },
  { text: "I sit with discomfort to learn.", author: "Elia Beaumont", category: "reflective" },
  { text: "I recognize when I need rest.", author: "Clara Moreau", category: "reflective" },
  { text: "Self-reflection prevents repetition.", author: "Adrian Solene", category: "reflective" },
  { text: "I become wiser each time I pause.", author: "Rosalie Dane", category: "reflective" },

  // 🌧 Sad (50 quotes)
  { text: "Pain introduced me to my strength.", author: "Elia Laurent", category: "sad" },
  { text: "I survived what tried to break me.", author: "Mira Solene", category: "sad" },
  { text: "Healing is slow, but it is happening.", author: "Theo Maris", category: "sad" },
  { text: "I outgrew what once hurt me.", author: "Celine Aure", category: "sad" },
  { text: "Some endings are quiet rescues.", author: "Armand Vale", category: "sad" },
  { text: "I carry the lesson, not the wound.", author: "Isla Ren", category: "sad" },
  { text: "Tears are not weakness. They are release.", author: "Lucien Artois", category: "sad" },
  { text: "I am softer, not smaller.", author: "Noelle Serein", category: "sad" },
  { text: "Pain refined me.", author: "Elio Marchand", category: "sad" },
  { text: "I let heartbreak teach me.", author: "Sabine Moreau", category: "sad" },
  { text: "What hurt me also shaped me.", author: "Julian Hart", category: "sad" },
  { text: "Healing does not need witnesses.", author: "Anaïs Bloom", category: "sad" },
  { text: "I allowed myself to grieve.", author: "Orion Wells", category: "sad" },
  { text: "Broken does not mean ruined.", author: "Fleur Bennett", category: "sad" },
  { text: "I chose growth over bitterness.", author: "Adrian Sol", category: "sad" },
  { text: "Some scars glow with wisdom.", author: "Camille Rowe", category: "sad" },
  { text: "I learned to sit with my sadness.", author: "Elias Monroe", category: "sad" },
  { text: "Pain passes. Strength stays.", author: "Rosalie Verne", category: "sad" },
  { text: "I am rebuilding quietly.", author: "Mateo Quinn", category: "sad" },
  { text: "Even shattered glass reflects light.", author: "Liora Dane", category: "sad" },
  { text: "I forgive to free myself.", author: "Vincent Hale", category: "sad" },
  { text: "Loss taught me clarity.", author: "Mae Laurent", category: "sad" },
  { text: "I did not collapse. I transformed.", author: "Daniel Croix", category: "sad" },
  { text: "Grief carved depth into me.", author: "Aria Linden", category: "sad" },
  { text: "I stopped begging what hurt me to stay.", author: "Soren Vale", category: "sad" },
  { text: "Healing requires honesty.", author: "Celeste Marin", category: "sad" },
  { text: "I became stronger in silence.", author: "Hugo Delacour", category: "sad" },
  { text: "Not everything that left was meant to remain.", author: "Elise Rowan", category: "sad" },
  { text: "I am learning to trust again.", author: "Nico Arden", category: "sad" },
  { text: "Sadness softened my judgment.", author: "Clara Fontaine", category: "sad" },
  { text: "I held myself when no one did.", author: "Leo Beaumont", category: "sad" },
  { text: "The storm passed. I remained.", author: "Ivy Solis", category: "sad" },
  { text: "I turned my pain into boundaries.", author: "Adrian Wolfe", category: "sad" },
  { text: "Every ending changed me.", author: "Mira Laurent", category: "sad" },
  { text: "I survived the nights I thought I wouldn't.", author: "Emile Hart", category: "sad" },
  { text: "I am healing at my own pace.", author: "Nora Vale", category: "sad" },
  { text: "My heart learned resilience.", author: "Julien Armand", category: "sad" },
  { text: "I stopped romanticizing what hurt me.", author: "Seraphine Cole", category: "sad" },
  { text: "I release what no longer respects me.", author: "Theo Linden", category: "sad" },
  { text: "Healing is not linear.", author: "Camille Arden", category: "sad" },
  { text: "I chose myself after the heartbreak.", author: "Elias Moreau", category: "sad" },
  { text: "Pain taught me discernment.", author: "Anais Laurent", category: "sad" },
  { text: "I am not ashamed of my tears.", author: "Lucas Fontaine", category: "sad" },
  { text: "I grow through what I go through.", author: "Isabelle Hart", category: "sad" },
  { text: "I deserve gentle love.", author: "Orion Vale", category: "sad" },
  { text: "My wounds became wisdom.", author: "Mae Soren", category: "sad" },
  { text: "I found clarity in loss.", author: "Elia Beaumont", category: "sad" },
  { text: "I am still worthy after everything.", author: "Clara Moreau", category: "sad" },
  { text: "Time did not erase it, but it strengthened me.", author: "Adrian Solene", category: "sad" },
  { text: "I healed without becoming hard.", author: "Rosalie Dane", category: "sad" },

  // 🌾 Grateful (50 quotes)
  { text: "Gratitude turns what I have into enough.", author: "Elia Laurent", category: "grateful" },
  { text: "I wake up thankful for another chance.", author: "Mira Solene", category: "grateful" },
  { text: "Even ordinary days deserve appreciation.", author: "Theo Maris", category: "grateful" },
  { text: "Contentment is quiet wealth.", author: "Celine Aure", category: "grateful" },
  { text: "I notice what is working.", author: "Armand Vale", category: "grateful" },
  { text: "Gratitude softens my worries.", author: "Isla Ren", category: "grateful" },
  { text: "I am thankful for lessons disguised as loss.", author: "Lucien Artois", category: "grateful" },
  { text: "There is abundance in simplicity.", author: "Noelle Serein", category: "grateful" },
  { text: "I count blessings, not lacks.", author: "Elio Marchand", category: "grateful" },
  { text: "Grateful hearts glow differently.", author: "Sabine Moreau", category: "grateful" },
  { text: "I appreciate how far I've come.", author: "Julian Hart", category: "grateful" },
  { text: "Thankfulness anchors me.", author: "Anaïs Bloom", category: "grateful" },
  { text: "I cherish small mercies.", author: "Orion Wells", category: "grateful" },
  { text: "Gratitude shifts perspective instantly.", author: "Fleur Bennett", category: "grateful" },
  { text: "I am thankful for growth.", author: "Adrian Sol", category: "grateful" },
  { text: "What I once prayed for is now my reality.", author: "Camille Rowe", category: "grateful" },
  { text: "I honor the present moment.", author: "Elias Monroe", category: "grateful" },
  { text: "Gratitude invites peace.", author: "Rosalie Verne", category: "grateful" },
  { text: "I give thanks for quiet mornings.", author: "Mateo Quinn", category: "grateful" },
  { text: "Enough is a powerful word.", author: "Liora Dane", category: "grateful" },
  { text: "I appreciate who I am becoming.", author: "Vincent Hale", category: "grateful" },
  { text: "Gratitude transforms comparison into contentment.", author: "Mae Laurent", category: "grateful" },
  { text: "I am thankful for second chances.", author: "Daniel Croix", category: "grateful" },
  { text: "Every breath is a gift.", author: "Aria Linden", category: "grateful" },
  { text: "I celebrate simple joys.", author: "Soren Vale", category: "grateful" },
  { text: "Thankfulness brings clarity.", author: "Celeste Marin", category: "grateful" },
  { text: "I am grateful for resilience.", author: "Hugo Delacour", category: "grateful" },
  { text: "There is beauty in what remains.", author: "Elise Rowan", category: "grateful" },
  { text: "I appreciate those who stayed.", author: "Nico Arden", category: "grateful" },
  { text: "Gratitude makes room for more.", author: "Clara Fontaine", category: "grateful" },
  { text: "I give thanks for my strength.", author: "Leo Beaumont", category: "grateful" },
  { text: "Grateful living feels lighter.", author: "Ivy Solis", category: "grateful" },
  { text: "I am thankful for lessons learned.", author: "Adrian Wolfe", category: "grateful" },
  { text: "Appreciation deepens happiness.", author: "Mira Laurent", category: "grateful" },
  { text: "I recognize the good around me.", author: "Emile Hart", category: "grateful" },
  { text: "Gratitude grounds ambition.", author: "Nora Vale", category: "grateful" },
  { text: "I honor my journey.", author: "Julien Armand", category: "grateful" },
  { text: "Thankfulness turns survival into blessing.", author: "Seraphine Cole", category: "grateful" },
  { text: "I see abundance where I once saw lack.", author: "Theo Linden", category: "grateful" },
  { text: "Gratitude is daily alignment.", author: "Camille Arden", category: "grateful" },
  { text: "I am thankful for today.", author: "Elias Moreau", category: "grateful" },
  { text: "Contentment begins with awareness.", author: "Anais Laurent", category: "grateful" },
  { text: "I appreciate quiet progress.", author: "Lucas Fontaine", category: "grateful" },
  { text: "Gratitude strengthens my faith in life.", author: "Isabelle Hart", category: "grateful" },
  { text: "I value what truly matters.", author: "Orion Vale", category: "grateful" },
  { text: "Thankfulness rewrites perspective.", author: "Mae Soren", category: "grateful" },
  { text: "I am grateful for love received.", author: "Elia Beaumont", category: "grateful" },
  { text: "There is richness in simplicity.", author: "Clara Moreau", category: "grateful" },
  { text: "I pause to give thanks.", author: "Adrian Solene", category: "grateful" },
  { text: "My heart rests in gratitude.", author: "Rosalie Dane", category: "grateful" },
];
