services:
  mongodb:
    image: mongo:7
    container_name: quote_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: quote_backend
    ports:
      - "3001:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  # frontend:
  #   build: ./frontend
  #   container_name: meme_frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

volumes:
  mongo_data:
